version: '3.8'
services:
  dev-db:
    image: postgres:latest
    container_name: realtor-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bazochka
      POSTGRES_DB: realtor-db
    ports:
      - 5433:5432